### ISSUE TITLE
Conky cant show battery

### ISSUE THREAD

**Issue by ashok-arora** [xexpanderx/Conky-Revisited-2#3]
I get the following error:
Conky: can't open /sys/class/power_supply/BAT0/uevent
and can't display battery status.

**Comment by xexpanderx** [comment]
BAT0 is the default parameter for battery status that conky is using. I believe you have another number after BAT-prefix, like say BAT1.

There is a workaround by symlinking BAT1 to BAT0. Verify that you use BAT1 by checking that BAT1 - directory exists in /sys/class/power_supply/

If so, you can do this:

```
sudo mkdir /sys/class/power_supply/BAT0
sudo ln -s /sys/class/power_supply/BAT1 /sys/class/power_supply/BAT0
sudo mkdir /proc/acpi/battery/BAT0
sudo ln -s /proc/acpi/battery/BAT1 /proc/acpi/battery/BAT0
```
Meantime, I have to find some time to put this option in the conky code :)

**Comment by xexpanderx** [comment]
I added an option in "settings.lua" file. Change the BAT0 in line:

`battery_number="BAT0"`

to your number.

**Comment by xexpanderx** [comment]
I'm closing this issue now, if you still have this problem, please open a new issue. Thank you!

**Comment by ashok-arora** [comment]
#### Solved
It seems to work perfectly now, thanks!
